// Find ActionType popularity for specific operating system // by jkb
let Win = DeviceInfo
| where OSPlatform == "Windows11"
| distinct DeviceId;
let CountDevice = Win
| summarize DeviceCount = todouble(count())
| extend Match = " ";
DeviceEvents
| where DeviceId in (Win)
| summarize DevicesWithActionCount = dcount(DeviceId, 4) by ActionType
| extend Match = " "
| join kind=inner CountDevice 
    on Match
| extend Percent = round((DevicesWithActionCount / DeviceCount) * 100, 3)
| project ActionType, Percent
